//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWorks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Appeals
    {
        [Required]
        [DisplayName("AppealId")]
        public int appealId { get; set; }
        [Required]
        [DisplayName("Description")]
        public string description { get; set; }
        [Required]
        [DisplayName("Entry DateTime")]
        public System.DateTime entryDatetime { get; set; }
        [Required]
        [DisplayName("Deadline DateTime")]
        public System.DateTime deadlineDatetime { get; set; }
    }
}
