//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWorks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Appeals
    {
        private DateTime currentDateTime = DateTime.Now;


        [Required]
        [DisplayName("AppealId")]
        public int appealId
        {
            get; set;
        }

        [Required]
        [DisplayName("Description")]
        public string description
        {
            get; set;
        }

        [Required]
        [DisplayName("Entry DateTime")]
        [DataType(DataType.DateTime)]
        public System.DateTime entryDatetime
        {
            get
            {
                return currentDateTime;
            }
            set
            {
                currentDateTime = value;
            }
        }


        [Required]
        [DisplayName("Deadline DateTime")]
        [DataType(DataType.DateTime)]
        [MyDate(ErrorMessage ="Deadline is in past!")]
        public System.DateTime deadlineDatetime
        {
            get; set;
        }
    }
    public class MyDateAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            DateTime futureDateTime = Convert.ToDateTime(value);
            return futureDateTime >= DateTime.Now;
        }
    }
}
